<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-4SJACL6" failures="2" tests="13" name="Test" time="90.897" errors="0" timestamp="2024-10-14T17:19:10 EDT">
  <testcase classname="com.naveenlabs.PageTests.AccountLoginPageTest" name="ForgotPasswordFunctionality" time="2.555"/>
  <testcase classname="com.naveenlabs.PageTests.AccountLoginPageTest" name="LoginWithInvalidCredentials" time="0.97">
    <skipped/>
  </testcase> <!-- LoginWithInvalidCredentials -->
  <testcase classname="com.naveenlabs.PageTests.AccountLoginPageTest" name="LoginWithInvalidCredentials" time="0.952">
    <failure type="java.lang.AssertionError" message="expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found [Warning: No match for E-Mail Address and/or Password.]">
      <![CDATA[java.lang.AssertionError: expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found [Warning: No match for E-Mail Address and/or Password.]
at com.naveenlabs.PageTests.AccountLoginPageTest.LoginWithInvalidCredentials(AccountLoginPageTest.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- LoginWithInvalidCredentials -->
  <testcase classname="com.naveenlabs.PageTests.AccountLoginPageTest" name="LoginWithInvalidEmailAndValidPassword" time="0.967"/>
  <testcase classname="com.naveenlabs.PageTests.AccountLoginPageTest" name="LoginWithValidCredentials" time="1.573"/>
  <testcase classname="com.naveenlabs.PageTests.AccountLoginPageTest" name="LoginWithValidEmailAndInvalidPassword" time="0.934"/>
  <testcase classname="com.naveenlabs.PageTests.ForgotYourPasswordPageTest" name="ForgotPasswordFunctionalityWithInvalidEmail" time="1.36"/>
  <testcase classname="com.naveenlabs.PageTests.AddressBookPageTest" name="ValidateAddedAddressBookDelete" time="2.919"/>
  <testcase classname="com.naveenlabs.PageTests.AddressBookPageTest" name="ValidateAddressBookNewAddress" time="5.578"/>
  <testcase classname="com.naveenlabs.PageTests.AddressBookPageTest" name="ValidateDefaultAddressBookDelete" time="2.636"/>
  <testcase classname="com.naveenlabs.PageTests.AddressBookPageTest" name="ValidateEditAddressBookDelete" time="4.257"/>
  <testcase classname="com.naveenlabs.PageTests.MyAccountPageTest" name="EditAccount" time="3.533">
    <skipped/>
  </testcase> <!-- EditAccount -->
  <testcase classname="com.naveenlabs.PageTests.MyAccountPageTest" name="EditAccount" time="3.409">
    <failure type="java.lang.AssertionError" message="expected [Success: Your account has been successfully updated.] but found [Success: Your account has been successfully update.]">
      <![CDATA[java.lang.AssertionError: expected [Success: Your account has been successfully updated.] but found [Success: Your account has been successfully update.]
at com.naveenlabs.PageTests.MyAccountPageTest.EditAccount(MyAccountPageTest.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- EditAccount -->
</testsuite> <!-- Test -->
